name: CD-NuGet



on:  
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x

    - name: Pack
      run: |
        dotnet pack ./Source/FikaAmazonAPI/*/*/*.csproj  Release

    - name: PushNuget
      run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
